import generated from "./keyboardPacks.generated.json";
import type { KeyboardPack } from "./types";

/**
 * Every pack folder found in public/audio/keys at the last `dev` / `build` / `test` run.
 * Generated by scripts/keyboard-packs.mjs: copy a pack folder in and restart, no editing needed.
 */
export const keyboardPacks: KeyboardPack[] = generated;
